source: site
paths:
  uploads: uploads
  collections: collections
  data: _data
  layouts: _layouts
  includes: _includes
collections_config:
  pages:
    path: collections/_pages
    output: true
    icon: wysiwyg
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  projects:
    path: collections/_projects
    output: true
    icon: work_outline
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  testimonials:
    path: collections/_testimonials
    output: false
    icon: format_quote
    _enabled_editors:
      - data
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  data:
    path: _data
    output: false
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  posts:
    path: collections/_posts
    output: true
    icon: notes
    create:
      path: >-
        [relative_base_path]/{date|year}-{date|month}-{date|day}-{title|slugify}.[ext]
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  drafts:
    path: collections/_drafts
    output: true
    icon: notes
    create:
      publish_to: posts
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  config _config.yml:
    path: config _config.yml
    output: true
    parse_branch_index: true
    icon: notes
    _editables: {}
    _inputs: {}
    _select_data: {}
    _structures: {}
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas: {}
collections_config_override: false
collection_groups:
  - heading: Content
    collections:
      - pages
      - projects
      - testimonials
  - heading: Blogging
    collections:
      - posts
      - drafts
  - heading: Settings
    collections:
      - data
_enabled_editors:
  - content
  - data
  - visual
_inputs:
  categories:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
  tags:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
_select_data: {}
_structures: {}
_editables: {}
data_config: {}
editor:
  default_path: config _config.yml
source_editor:
  tab_size: 2
  theme: monokai
  show_gutter: true
timezone: Etc/UTC
